phrases = ['bake off', 'bake sale', 'bake well', 'bath mat', 'bath mat', 'bath robe', 
		   'bath room', 'bath salts', 'bath sponge', 'bath towel', 'bed room', 'black belt', 
		   'black board', 'black smith', 'black stone', 'board cover', 'board game', 'board meeting', 
		   'board room', 'board walk', 'book shelf', 'bottle cap', 'bottle neck', 'bottle opener', 
		   'boy scout', 'building manager', 'camp fire', 'camp ground', 'camp site', 'cap gun', 
		   'cap stone', 'chain link', 'chain mail', 'chain reaction', 'chain saw', 'code switch', 
		   'done for', 'easy bake', 'easy living', 'fence gate', 'fence line', 'fence post', 
		   'game board', 'game card', 'game master', 'game night', 'game on', 'game over', 
		   'game room', 'game token', 'garden gate', 'garden path', 'garden room', 'garden wall', 
		   'general manager', 'general store', 'girl scout', 'green house', 'guest bed', 'guest room', 
		   'hot topic', 'in side', 'kitchen sink', 'last word', 'leader board', 'light beam', 
		   'light house', 'light switch', 'link fence', 'lock box', 'lock pick', 'lock smith', 
		   'lock step', 'mail box', 'mail carrier', 'mail room', 'mail route', 'mail slot', 
		   'master bath', 'master chief', 'mix bowl', 'mix tape', 'mountain pass', 'mountain trail', 
		   'ocean breeze', 'off side', 'office building', 'office chair', 'office door', 'office light', 
		   'office space', 'over easy', 'post card', 'post code', 'post mark', 'post office', 
		   'room mate', 'scout badge', 'scout camp', 'scout leader', 'scout troop', 'show girl', 
		   'sink hole', 'slide show', 'sponge bath', 'stone bridge', 'stone floor', 'stone path', 
		   'stone step', 'stone wall', 'store room', 'switch blade', 'switch board', 'switch gear', 
		   'tape recorder', 'trail guide', 'trail head', 'trail map', 'trail mix', 'trail sign', 
		   'water bottle', 'water front', 'water line', 'water mark', 'water pipe', 'water slide', 
		   'water softener', 'water well', 'well done', 'word game', 'word smith', 'apple pie',
		   'pie crust', 'granny smith', 'apple tart', 'wood panel', 'panel show', "stone quarry", 
		   "trail runner", "office plant", "board member", "mail truck", "post route", 
		   "garden shed", "room key", "switch lock", "water shed", "game show", "stone arch", "board fence", 
		   "trail junction", "water tank", "light post", "stop light", "cross road", "road runner", "runner up",
		   "up side", "upside down", "down side", "out side", "side on", "tape worm", "tape dispenser", 
		   "worm hole", "hole punch", "hole cutter", "hole saw", "hole cover", "hole filler", "hole trap", 
		   "hole plug", "hole opener", "hole drill", "hole finder", "show stopper", "show stop", "stop light", 
		   "stop sign", "down vote", "down payment", "down time", "down stairs", "down town", "down hill", 
		   "down load", "down pour", "down draft", "down swing", "up time", "up town", "up hill", "up stairs",
		    "side door", "side walk", "side table", "side mirror", "side window", "side panel", "side track", 
		    "side street", "side wall", "side view", "smith shop", "shop keep", "apple orchard", "pizza crust",
		    "bath bomb", "word play", "code word",  "trail blaze", "camp stove", "game piece", 
		    "lock jaw", "board state", "mail bag"]


